#!/usr/bin/env python3
"""CLI entry point for the ``astra-discover`` command."""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional

from src import run_advanced_discovery, run_basic_discovery, system_check

__all__ = [
    "main",
    "__version__",
]

__version__ = "2.0.2"

DEFAULT_RESULTS_DIR = "discoveries"
TOP_ANOMALIES_TO_SHOW = 3


@dataclass
class RunArtifacts:
    """Paths to files generated by a discovery run."""

    report: Optional[Path] = None
    catalog: Optional[Path] = None
    summary: Optional[Path] = None


def _prepare_output_dir(output: str, mode: str) -> Path:
    """Determine and create the output directory for this run."""

    timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    if output == "auto":
        base = Path.cwd() / DEFAULT_RESULTS_DIR
        base.mkdir(parents=True, exist_ok=True)
        target = base / f"{mode}_run_{timestamp}"
    else:
        target = Path(output).expanduser()

    target.mkdir(parents=True, exist_ok=True)
    return target


def _render_summary(results: dict, mode: str) -> str:
    """Build a human-readable summary for the run."""

    transients = results.get("transients")
    anomalies = results.get("anomalies") or []

    lines: List[str] = []
    lines.append(f"ASTRA {mode.title()} Discovery Summary")
    lines.append("=" * 60)
    lines.append(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    if transients is not None:
        lines.append(f"Transients analyzed: {len(transients)}")
    lines.append(f"High-priority anomalies: {len(anomalies)}")
    lines.append("")

    if anomalies:
        lines.append("Top candidates:")
        for idx, anomaly in enumerate(anomalies[:TOP_ANOMALIES_TO_SHOW], 1):
            mag = anomaly.get("mag")
            mag_text = f"m={mag:.1f}" if mag is not None else "m=unknown"
            lines.append(
                f" {idx}. {anomaly.get('id', 'unknown')} "
                f"(Score: {anomaly.get('score', 0):.1f}, {mag_text}, "
                f"Type: {anomaly.get('type', 'unknown')})"
            )
            reasons = ", ".join(anomaly.get("reasons", [])[:3])
            if reasons:
                lines.append(f"    Reasons: {reasons}")
        lines.append("")

    lines.append("Next steps:")
    lines.append("  • Review the report for observation targets")
    lines.append("  • Schedule follow-up or re-run with --advanced/--basic as needed")

    return "\n".join(lines)


def _write_results(results: dict, output_dir: Path, mode: str) -> RunArtifacts:
    """Persist discovery artifacts to disk."""

    artifacts = RunArtifacts()

    report_text = results.get("report")
    if report_text:
        report_path = output_dir / f"astra_{mode}_report.txt"
        report_path.write_text(report_text, encoding="utf-8")
        artifacts.report = report_path

    transients = results.get("transients")
    if transients is not None:
        catalog_path = output_dir / f"{mode}_transients_catalog.csv"
        transients.to_csv(catalog_path, index=False)
        artifacts.catalog = catalog_path

    summary_path = output_dir / "summary.txt"
    summary_path.write_text(_render_summary(results, mode), encoding="utf-8")
    artifacts.summary = summary_path

    latest_symlink = Path.cwd() / "latest_discovery"
    try:
        if latest_symlink.is_symlink() or latest_symlink.exists():
            latest_symlink.unlink()
        latest_symlink.symlink_to(output_dir)
    except OSError:
        # Symlinks are best-effort (especially on Windows)
        pass

    return artifacts


def _print_run_header(mode: str) -> None:
    print("🚀 ASTRA Discovery System")
    print("========================")
    print(f"Mode: {mode.title()}")
    print(f"Start: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("")


def _print_run_summary(results: dict) -> None:
    anomalies = results.get("anomalies") or []
    transients = results.get("transients")
    transients_count = len(transients) if transients is not None else 0

    print("📊 Discovery Summary")
    print("--------------------")
    print(f"Transients analyzed: {transients_count}")
    print(f"High-priority anomalies: {len(anomalies)}")

    if anomalies:
        print("")
        print("Top candidates:")
        for idx, anomaly in enumerate(anomalies[:TOP_ANOMALIES_TO_SHOW], 1):
            mag = anomaly.get("mag")
            mag_text = f"m={mag:.1f}" if mag is not None else "m=unknown"
            print(
                f" {idx}. {anomaly.get('id', 'unknown')} "
                f"(Score: {anomaly.get('score', 0):.1f}, {mag_text}, "
                f"Type: {anomaly.get('type', 'unknown')})"
            )
    print("")


def _run_quick_test(verbose: bool = False) -> int:
    """Run lightweight checks without touching the network."""

    print("🔍 Running ASTRA self-test (no network calls)...")
    ok = system_check()
    if not ok:
        print("❌ System check failed. See messages above.")
        return 1

    try:
        if not callable(run_basic_discovery):  # pragma: no cover - defensive
            raise RuntimeError("run_basic_discovery is not callable")
        print("✅ Core discovery functions available")
    except Exception as exc:  # pragma: no cover - defensive
        print(f"❌ Unable to import discovery pipeline: {exc}")
        return 1

    print("🎉 ASTRA installation looks good. Run with --advanced to begin discovering!")
    return 0


def _execute_pipeline(mode: str) -> Optional[dict]:
    """Run the requested discovery pipeline."""

    if mode == "advanced":
        return run_advanced_discovery()
    return run_basic_discovery()


def main(argv: Optional[Iterable[str]] = None) -> int:
    """CLI entry point used by console_scripts."""

    parser = argparse.ArgumentParser(
        description="Run the ASTRA discovery pipelines without shell scripts",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  astra-discover --advanced\n"
            "  astra-discover --basic --output results/\n"
            "  astra-discover --test\n"
            "  astra-discover --check\n"
        ),
    )
    parser.add_argument(
        "--advanced",
        action="store_true",
        help="Run the enhanced discovery pipeline (default)",
    )
    parser.add_argument(
        "--basic",
        action="store_true",
        help="Run the legacy basic discovery pipeline",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Run dependency and environment checks only",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Lightweight self-test without fetching external data",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default="auto",
        help="Directory for run artifacts (default: discoveries/<timestamp>)",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Show extra logging (reserved for future use)",
    )

    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.check:
        ok = system_check()
        return 0 if ok else 1

    if args.test:
        return _run_quick_test(verbose=args.verbose)

    mode = "advanced"
    if args.basic and not args.advanced:
        mode = "basic"

    _print_run_header(mode)

    try:
        results = _execute_pipeline(mode)
    except KeyboardInterrupt:
        print("\n⚠️ Discovery interrupted by user")
        return 1
    except Exception as exc:  # pragma: no cover - defensive
        print(f"\n❌ Discovery pipeline failed: {exc}")
        return 1

    if not results:
        print("❌ No results returned. Check logs above.")
        return 1

    _print_run_summary(results)

    output_dir = _prepare_output_dir(args.output, mode)
    artifacts = _write_results(results, output_dir, mode)

    print("📁 Artifacts saved to:")
    if artifacts.report:
        print(f"  • Report:  {artifacts.report}")
    if artifacts.catalog:
        print(f"  • Catalog: {artifacts.catalog}")
    if artifacts.summary:
        print(f"  • Summary: {artifacts.summary}")
    print("")
    print("Next steps: review the report and plan follow-up observations.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
